//
//  GalleryCategoryStyleSheet.js
//  Burp
//
//  Created by Abhishek Bhagwat.
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	galleryCategoryView: {
		backgroundColor: "white",
		flex: 1,
		alignItems: "center",
	},
	headerView: {
		backgroundColor: "transparent",
		marginTop: 21,
		width: 325,
		height: 20.5,
		flexDirection: "row",
		alignItems: "center",
	},
	headerMenuDarkButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		width: 16.5,
		height: 11,
	},
	headerMenuDarkButtonImage: {
		resizeMode: "contain",
	},
	headerMenuDarkButtonText: {
		color: "black",
		fontFamily: ".SFNSText",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	cartButtonButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		width: 12,
		height: 12,
	},
	cartButtonButtonImage: {
		resizeMode: "contain",
	},
	cartButtonButtonText: {
		color: "black",
		fontFamily: ".SFNSText",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	browseText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
	},
	categoryButton: {
		backgroundColor: "transparent",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		marginTop: 33,
		width: 325,
		height: 232,
	},
	categoryButtonImage: {
		resizeMode: "contain",
		marginBottom: 19,
	},
	categoryButtonText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	categoryTwoView: {
		backgroundColor: "transparent",
		marginTop: 17,
		width: 325,
		height: 232,
	},
	bitmapTwoImage: {
		resizeMode: "cover",
		backgroundColor: "transparent",
		height: 162.5,
		width: null,
	},
	titleTwoText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginLeft: 1,
		marginBottom: 2,
	},
	categoryView: {
		backgroundColor: "transparent",
		width: 326,
		height: 207.5,
	},
	bitmapImage: {
		resizeMode: "cover",
		backgroundColor: "transparent",
		marginRight: 1,
		height: null,
		flex: 1,
	},
	statsView: {
		backgroundColor: "transparent",
		marginLeft: 25,
		marginTop: 128,
		width: 64,
		height: 13,
		flexDirection: "row",
		alignItems: "center",
	},
	likesView: {
		backgroundColor: "transparent",
		width: 30.5,
		height: 13,
		flexDirection: "row",
		alignItems: "center",
	},
	heartFontawesomeImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		height: 6.43,
		flex: 1,
	},
	countThreeText: {
		color: "white",
		fontFamily: "Avenir-Light",
		fontSize: 8,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 13,
		backgroundColor: "transparent",
		marginLeft: 3,
		flex: 1,
	},
	messageView: {
		backgroundColor: "transparent",
		width: 23.5,
		height: 13,
		flexDirection: "row",
		alignItems: "center",
	},
	chatBubbleMaterialImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		height: 6.82,
		flex: 1,
	},
	countTwoText: {
		color: "white",
		fontFamily: "Avenir-Light",
		fontSize: 8,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 13,
		backgroundColor: "transparent",
		marginLeft: 3,
		flex: 1,
	},
	titleText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginLeft: 1,
		marginBottom: 1,
	},
	countText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Light",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 16,
		backgroundColor: "transparent",
		marginBottom: 3,
	},
})

export default styles
