//
//  PaymentDetailsStyleSheet.js
//  Burp
//
//  Created by Abhishek Bhagwat.
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	paymentDetailsView: {
		backgroundColor: "white",
		flex: 1,
		alignItems: "center",
	},
	headerView: {
		backgroundColor: "transparent",
		marginTop: 21,
		width: 325,
		height: 20.5,
		flexDirection: "row",
		alignItems: "center",
	},
	headerMenuDarkImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 16.5,
		height: 11,
	},
	headerOptionsDarkImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 12,
		height: 12,
	},
	paymentDetailsText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
	},
	cardView: {
		backgroundColor: "rgb(0, 188, 212)",
		borderRadius: 6,
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 10.5,
		shadowOpacity: 1,
		marginTop: 34,
		width: 325,
		height: 174.5,
	},
	cardNumberTwoText: {
		color: "white",
		fontFamily: "Avenir-Light",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 16,
		backgroundColor: "transparent",
		marginLeft: 25,
		marginTop: 37,
	},
	visaImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		marginRight: 22,
		marginTop: 22,
		width: 37.26,
		height: null,
	},
	numberText: {
		color: "white",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginLeft: 24,
		marginTop: 2,
		alignSelf: "flex-start",
	},
	cardOwnerTwoText: {
		color: "white",
		fontFamily: "Avenir-Light",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 16,
		backgroundColor: "transparent",
		marginLeft: 25,
		marginTop: 32,
	},
	issuedText: {
		color: "white",
		fontFamily: "Avenir-Light",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 16,
		backgroundColor: "transparent",
		marginRight: 35,
		marginTop: 59,
	},
	expireText: {
		color: "white",
		fontFamily: "Avenir-Light",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 16,
		backgroundColor: "transparent",
		marginRight: 34,
		marginTop: 48,
	},
	nameText: {
		color: "white",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginLeft: 24,
		marginBottom: 19,
	},
	monthText: {
		color: "white",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginRight: 23,
		marginBottom: 19,
	},
	monthTwoText: {
		color: "white",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginRight: 22,
		marginBottom: 19,
	},
	addNewFormView: {
		backgroundColor: "transparent",
		marginTop: 45,
		width: 326.5,
		height: 330,
	},
	titleText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 18,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 29,
		backgroundColor: "transparent",
	},
	ownerView: {
		backgroundColor: "rgb(238, 238, 238)",
		borderRadius: 25,
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6.5,
		shadowOpacity: 1,
		marginLeft: 1,
		marginTop: 28,
		height: 50,
		flexDirection: "row",
		alignItems: "center",
	},
	personMaterialImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		marginLeft: 25,
		width: 10,
		height: 10,
	},
	cardOwnerText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginLeft: 9,
	},
	numberView: {
		backgroundColor: "rgb(238, 238, 238)",
		borderRadius: 25,
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6.5,
		shadowOpacity: 1,
		marginLeft: 1,
		marginTop: 25,
		height: 50,
		flexDirection: "row",
		alignItems: "center",
	},
	icon24pxThreeImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		marginLeft: 24,
		width: 12,
		height: 12,
	},
	cardNumberText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginLeft: 8,
	},
	monthView: {
		backgroundColor: "rgb(238, 238, 238)",
		borderRadius: 25,
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6.5,
		shadowOpacity: 1,
		marginLeft: 1,
		marginTop: 25,
		width: 150,
		height: 50,
		flexDirection: "row",
		alignItems: "center",
	},
	icon24pxImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		marginLeft: 24,
		height: 12,
		flex: 1,
	},
	expMonthText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginLeft: 8,
		marginRight: 26,
		flex: 1,
	},
	yearView: {
		backgroundColor: "rgb(238, 238, 238)",
		borderRadius: 25,
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6.5,
		shadowOpacity: 1,
		marginTop: 25,
		width: 150,
		height: 50,
		flexDirection: "row",
		alignItems: "center",
	},
	icon24pxTwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		marginLeft: 24,
		height: 12,
		flex: 1,
	},
	expYearText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginLeft: 8,
		flex: 1,
	},
	buttonView: {
		backgroundColor: "rgb(0, 188, 212)",
		borderRadius: 25,
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 7.5,
		shadowOpacity: 1,
		marginLeft: 1,
		height: 50,
		justifyContent: "center",
		alignItems: "center",
	},
	addNewCardText: {
		color: "white",
		fontFamily: "Avenir-Medium",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		lineHeight: 16,
		paddingTop: 6,
		backgroundColor: "transparent",
	},
})

export default styles
