//
//  NavigationMenuStyleSheet.js
//  Burp
//
//  Created by Abhishek Bhagwat.
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	navigationMenuView: {
		backgroundColor: "white",
		flex: 1,
		justifyContent: "center",
	},
	menuBackground2View: {
		backgroundColor: "rgb(0, 188, 212)",
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 10.5,
		shadowOpacity: 1,
		width: 275,
		height: 667,
		alignItems: "flex-start",
	},
	userInfoView: {
		backgroundColor: "transparent",
		marginLeft: 24,
		marginTop: 65,
		width: 202,
		height: 90.59,
	},
	imageImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 10.5,
		shadowOpacity: 1,
		marginLeft: 1,
		width: null,
		height: 50,
	},
	nameText: {
		color: "white",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginTop: 13,
	},
	postText: {
		color: "white",
		fontFamily: "Avenir-Light",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 21,
		backgroundColor: "transparent",
	},
	profileButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		marginLeft: 24,
		marginTop: 78,
		width: 89.5,
		height: 22,
	},
	profileButtonImage: {
		resizeMode: "contain",
		marginRight: 10,
	},
	profileButtonText: {
		color: "white",
		fontFamily: "Avenir-Medium",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	messagesButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		marginLeft: 24,
		marginTop: 28,
		width: 110,
		height: 22,
	},
	messagesButtonImage: {
		resizeMode: "contain",
		marginRight: 10,
	},
	messagesButtonText: {
		color: "white",
		fontFamily: "Avenir-Medium",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	statsButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		marginLeft: 24,
		marginTop: 28,
		width: 89,
		height: 22,
	},
	statsButtonImage: {
		resizeMode: "contain",
		marginRight: 10,
	},
	statsButtonText: {
		color: "white",
		fontFamily: "Avenir-Medium",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	settingsView: {
		backgroundColor: "transparent",
		marginLeft: 23,
		marginTop: 28,
		width: 101.5,
		height: 22,
		flexDirection: "row",
		alignItems: "center",
	},
	icon24pxTwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		height: 12,
		flex: 1,
	},
	settingsText: {
		color: "white",
		fontFamily: "Avenir-Medium",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 13,
		flex: 1,
	},
	signoutView: {
		backgroundColor: "transparent",
		marginLeft: 23,
		marginBottom: 61,
		width: 103,
		height: 22,
		flexDirection: "row",
		alignItems: "center",
	},
	icon24pxImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		height: 12,
		flex: 1,
	},
	signoutText: {
		color: "white",
		fontFamily: "Avenir-Medium",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		backgroundColor: "transparent",
		marginLeft: 14,
		flex: 1,
	},
})

export default styles
