//
//  ProductDetailsStyleSheet.js
//  Burp
//
//  Created by Abhishek Bhagwat.
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	productDetailsView: {
		backgroundColor: "white",
		flex: 1,
	},
	imageImage: {
		resizeMode: "cover",
		backgroundColor: "transparent",
		marginRight: -189,
		height: null,
		flex: 1,
	},
	headerView: {
		backgroundColor: "transparent",
		marginTop: 21,
		width: 325,
		height: 20.5,
		flexDirection: "row",
		alignItems: "center",
	},
	headerMenuWhiteImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 16.5,
		height: 11,
	},
	headerOptionsWhiteImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 12,
		height: 12,
	},
	productDetailsText: {
		color: "white",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
	},
	likesView: {
		backgroundColor: "transparent",
		marginRight: 24,
		marginTop: 28,
		width: 50.5,
		height: 21,
		alignSelf: "flex-end",
		flexDirection: "row",
		alignItems: "center",
	},
	heartFontawesomeImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		height: 9,
		flex: 1,
	},
	countText: {
		color: "white",
		fontFamily: "Avenir-Light",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 21,
		backgroundColor: "transparent",
		marginLeft: 7,
		flex: 1,
	},
	priceText: {
		color: "white",
		fontFamily: "Avenir-Medium",
		fontSize: 21,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 34,
		backgroundColor: "transparent",
		marginRight: 36,
		marginTop: 232,
	},
	textTwoText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Light",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 21,
		backgroundColor: "transparent",
		marginLeft: 24,
		width: 126,
	},
	sizeView: {
		backgroundColor: "transparent",
		marginRight: 51,
		marginTop: 26,
		width: 45.5,
		height: 49.5,
	},
	titleTwoText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 11,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 18,
		backgroundColor: "transparent",
	},
	boxButton: {
		backgroundColor: "white",
		borderRadius: 3,
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 10.5,
		shadowOpacity: 1,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		marginTop: 7,
		height: 25,
		flex: 1,
	},
	boxButtonImage: {
		resizeMode: "contain",
	},
	boxButtonText: {
		color: "black",
		fontFamily: ".SFNSText",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	lText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Light",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 21,
		backgroundColor: "transparent",
		marginLeft: 16,
		marginTop: 8,
	},
	quantityView: {
		backgroundColor: "transparent",
		marginRight: 25,
		width: 75.5,
		height: 49.5,
	},
	titleText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 11,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 18,
		backgroundColor: "transparent",
		marginRight: 19,
		flex: 1,
	},
	boxView: {
		backgroundColor: "white",
		borderRadius: 3,
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 10.5,
		shadowOpacity: 1,
		marginTop: 7,
		height: 25,
		flex: 1,
		alignItems: "flex-start",
	},
	textText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Light",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 21,
		backgroundColor: "transparent",
		marginTop: 8,
	},
	quantityDecreaseButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		marginLeft: 9,
		marginTop: 3,
		width: 7,
		height: 21,
	},
	quantityDecreaseButtonImage: {
		resizeMode: "contain",
		marginRight: 10,
	},
	quantityDecreaseButtonText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Light",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	quantityIncreaseText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Light",
		fontSize: 13,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 21,
		backgroundColor: "transparent",
		marginRight: 7,
		marginTop: 8,
	},
	buyNowButton: {
		backgroundColor: "rgb(0, 188, 212)",
		borderRadius: 25,
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 7.5,
		shadowOpacity: 1,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		marginLeft: 25,
		marginBottom: 42,
		width: 150,
		height: 50,
	},
	buyNowButtonImage: {
		resizeMode: "contain",
		marginRight: 10,
	},
	buyNowButtonText: {
		color: "white",
		fontFamily: "Avenir-Medium",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
	},
	addToCartButton: {
		backgroundColor: "transparent",
		borderRadius: 25,
		borderWidth: 1.5,
		borderColor: "rgb(0, 188, 212)",
		borderStyle: "solid",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		marginRight: 25,
		marginBottom: 42,
		width: 150,
		height: 50,
	},
	addToCartButtonImage: {
		resizeMode: "contain",
		marginRight: 10,
	},
	addToCartButtonText: {
		color: "rgb(0, 188, 212)",
		fontFamily: "Avenir-Medium",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
	},
})

export default styles
