//
//  EditUserProfileStyleSheet.js
//  Burp
//
//  Created by Abhishek Bhagwat.
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	editUserProfileView: {
		backgroundColor: "white",
		flex: 1,
		alignItems: "center",
	},
	headerView: {
		backgroundColor: "transparent",
		marginTop: 21,
		width: 325,
		height: 20.5,
		flexDirection: "row",
		alignItems: "center",
	},
	headerMenuDarkButton: {
		backgroundColor: "transparent",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		width: 16.5,
		height: 11,
	},
	headerMenuDarkButtonImage: {
		resizeMode: "contain",
	},
	headerMenuDarkButtonText: {
		color: "black",
		fontFamily: ".SFNSText",
		fontSize: 12,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
	},
	headerOptionsDarkImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 12,
		height: 12,
	},
	editProfileText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
	},
	imageView: {
		backgroundColor: "transparent",
		marginRight: 115,
		marginTop: 58,
		width: 135,
		height: 125,
		alignSelf: "flex-end",
		justifyContent: "center",
	},
	bitmapImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		marginRight: 10,
		height: 125,
		width: null,
	},
	editImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		marginBottom: 15,
		width: 20,
		height: 20,
	},
	nameView: {
		backgroundColor: "rgb(238, 238, 238)",
		borderRadius: 25,
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6.5,
		shadowOpacity: 1,
		marginTop: 50,
		width: 325,
		height: 50,
		flexDirection: "row",
		alignItems: "center",
	},
	personMaterialImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		marginLeft: 25,
		width: 10,
		height: 10,
	},
	fullNameText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginLeft: 9,
	},
	dobView: {
		backgroundColor: "rgb(238, 238, 238)",
		borderRadius: 25,
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6.5,
		shadowOpacity: 1,
		marginTop: 25,
		width: 325,
		height: 50,
		flexDirection: "row",
		alignItems: "center",
	},
	icon24pxThreeImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		marginLeft: 23,
		width: 11.5,
		height: 12,
	},
	dateOfBirthText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginLeft: 9,
	},
	emailView: {
		backgroundColor: "rgb(238, 238, 238)",
		borderRadius: 25,
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6.5,
		shadowOpacity: 1,
		marginTop: 25,
		width: 325,
		height: 50,
		flexDirection: "row",
		alignItems: "center",
	},
	icon24pxTwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		marginLeft: 24,
		width: 11,
		height: 11,
	},
	emailAddressText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginLeft: 9,
	},
	mobileView: {
		backgroundColor: "rgb(238, 238, 238)",
		borderRadius: 25,
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 6.5,
		shadowOpacity: 1,
		marginBottom: 25,
		width: 325,
		height: 50,
		flexDirection: "row",
		alignItems: "center",
	},
	icon24pxImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		marginLeft: 23,
		width: 11.5,
		height: 11.5,
	},
	mobileNumberText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginLeft: 9,
	},
	buttonView: {
		backgroundColor: "rgb(0, 188, 212)",
		borderRadius: 25,
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 7.5,
		shadowOpacity: 1,
		marginBottom: 42,
		width: 325,
		height: 50,
		justifyContent: "center",
		alignItems: "center",
	},
	updateProfileText: {
		color: "white",
		fontFamily: "Avenir-Medium",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		lineHeight: 16,
		paddingTop: 6,
		backgroundColor: "transparent",
	},
})

export default styles
