//
//  CheckoutStyleSheet.js
//  Burp
//
//  Created by Abhishek Bhagwat.
//  Copyright © 2018 [Company]. All rights reserved.
//

import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
	checkoutView: {
		backgroundColor: "white",
		flex: 1,
		alignItems: "center",
	},
	headerView: {
		backgroundColor: "transparent",
		marginTop: 21,
		width: 325,
		height: 20.5,
		flexDirection: "row",
		alignItems: "center",
	},
	headerMenuDarkImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 16.5,
		height: 11,
	},
	headerOptionsDarkImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		width: 12,
		height: 12,
	},
	checkoutText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		backgroundColor: "transparent",
	},
	titleText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 18,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 29,
		backgroundColor: "transparent",
		marginLeft: 24,
		marginTop: 51,
		alignSelf: "stretch",
	},
	paypalView: {
		backgroundColor: "white",
		borderRadius: 6,
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 10.5,
		shadowOpacity: 1,
		marginTop: 28,
		width: 325,
		height: 75,
		flexDirection: "row",
	},
	imageImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		marginLeft: 25,
		width: 50,
		height: 50,
		alignSelf: "center",
	},
	methodNameFourText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginLeft: 16,
		marginTop: 10,
	},
	valueFourText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Light",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 16,
		backgroundColor: "transparent",
		marginLeft: 17,
		marginTop: 7,
	},
	checkFourImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		marginRight: 25,
		width: 25,
		height: 18,
	},
	visaView: {
		backgroundColor: "white",
		borderRadius: 6,
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 10.5,
		shadowOpacity: 1,
		marginTop: 25,
		width: 325,
		height: 75,
		flexDirection: "row",
	},
	imageThreeView: {
		backgroundColor: "white",
		borderRadius: 3,
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 8,
		shadowOpacity: 1,
		marginLeft: 25,
		width: 50,
		height: 50,
		alignSelf: "center",
		justifyContent: "center",
	},
	bitmapTwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		marginLeft: 6,
		marginRight: 6,
		height: 12.01,
		width: null,
	},
	methodNameThreeText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginLeft: 16,
		marginTop: 10,
	},
	valueThreeText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Light",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 16,
		backgroundColor: "transparent",
		marginLeft: 17,
		marginTop: 7,
	},
	checkThreeImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		marginRight: 25,
		width: 25,
		height: 18,
	},
	mastercardView: {
		backgroundColor: "white",
		borderRadius: 6,
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 10.5,
		shadowOpacity: 1,
		marginTop: 25,
		width: 325,
		height: 75,
		flexDirection: "row",
	},
	imageView: {
		backgroundColor: "white",
		borderRadius: 3,
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 8,
		shadowOpacity: 1,
		marginLeft: 25,
		width: 50,
		height: 50,
		alignSelf: "center",
		justifyContent: "center",
	},
	bitmapImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		height: 50,
		width: null,
	},
	methodNameText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginLeft: 16,
		marginTop: 10,
	},
	valueText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Light",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 16,
		backgroundColor: "transparent",
		marginLeft: 17,
		marginTop: 7,
	},
	checkImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		marginRight: 25,
		width: 25,
		height: 18,
	},
	mastercardCopyView: {
		backgroundColor: "white",
		borderRadius: 6,
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 10.5,
		shadowOpacity: 1,
		marginTop: 25,
		width: 325,
		height: 75,
		flexDirection: "row",
	},
	imageTwoView: {
		backgroundColor: "white",
		borderRadius: 3,
		shadowColor: "rgba(0, 0, 0, 0.05)",
		shadowRadius: 8,
		shadowOpacity: 1,
		marginLeft: 25,
		width: 50,
		height: 50,
		alignSelf: "center",
		justifyContent: "center",
	},
	netsLogoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		height: 23.86,
		width: null,
	},
	methodNameTwoText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Medium",
		fontSize: 15,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 24.5,
		backgroundColor: "transparent",
		marginLeft: 16,
		marginTop: 10,
	},
	valueTwoText: {
		color: "rgb(117, 117, 117)",
		fontFamily: "Avenir-Light",
		fontSize: 10,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "left",
		lineHeight: 16,
		backgroundColor: "transparent",
		marginLeft: 17,
		marginTop: 7,
	},
	checkTwoImage: {
		resizeMode: "center",
		backgroundColor: "transparent",
		marginRight: 25,
		width: 25,
		height: 18,
	},
	buttonView: {
		backgroundColor: "rgb(0, 188, 212)",
		borderRadius: 25,
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 7.5,
		shadowOpacity: 1,
		marginBottom: 41,
		width: 325,
		height: 50,
		justifyContent: "center",
		alignItems: "center",
	},
	continueText: {
		color: "white",
		fontFamily: "Avenir-Medium",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
		lineHeight: 16,
		paddingTop: 6,
		backgroundColor: "transparent",
	},
	continueBuyButton: {
		backgroundColor: "rgb(0, 188, 212)",
		borderRadius: 25,
		shadowColor: "rgba(0, 0, 0, 0.07)",
		shadowRadius: 7.5,
		shadowOpacity: 1,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		marginBottom: 41,
		width: 325,
		height: 50,
	},
	continueBuyButtonImage: {
		resizeMode: "contain",
		marginRight: 10,
	},
	continueBuyButtonText: {
		color: "white",
		fontFamily: "Avenir-Medium",
		fontSize: 16,
		fontStyle: "normal",
		fontWeight: "normal",
		textAlign: "center",
	},
})

export default styles
